@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Database/all.puml
!include AWSPuml/Storage/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
WAF(waf,"AWS WAF")
APIGateway(apiA,"Regional API A")
APIGateway(apiB,"Regional API B")
Lambda(appA,"Application Region A")
Lambda(appB,"Application Region B")
DynamoDB(ddbA,"DynamoDB Region A")
DynamoDB(ddbB,"DynamoDB Region B")
SimpleStorageService(s3A,"S3 Region A")
SimpleStorageService(s3B,"S3 Region B")
CloudWatch(cw,"CloudWatch Health")
waf --> apiA
waf --> apiB
apiA --> appA
apiB --> appB
appA --> ddbA
appB --> ddbB
ddbA <--> ddbB
s3A <--> s3B
appA --> cw
appB --> cw
@enduml