@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
WAF(waf,"AWS WAF")
Lambda(honey1,"Honeypot Workload A")
Lambda(honey2,"Honeypot Workload B")
CloudWatch(cw,"Telemetry")
KinesisDataStreams(stream,"Kinesis Data Streams")
SecurityLake(lake,"Amazon Security Lake")
OpenSearchService(os,"OpenSearch Investigations")
SecurityHub(hub,"Security Hub")
Detective(det,"Amazon Detective")
waf --> honey1
waf --> honey2
honey1 --> cw
honey2 --> cw
cw --> stream
stream --> lake
lake --> os
lake --> hub
hub --> det
@enduml