@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Containers/all.puml
!include AWSPuml/ManagementGovernance/all.puml

left to right direction
rectangle "Consumer VPC 10.10.0.0/16" {
  ElasticKubernetesService(consumer,"Consumer EKS")
  VPCEndpoints(ep,"Interface VPC Endpoint")
}
rectangle "Provider VPC 10.40.0.0/16" {
  PrivateLink(pl,"Endpoint Service")
  ElasticLoadBalancingNetworkLoadBalancer(nlb,"NLB")
  EC2(app,"Private Service")
}
TransitGateway(tgw,"Optional TGW for other networks")
CloudWatch(cw,"CloudWatch")
consumer --> ep
ep --> pl
pl --> nlb
nlb --> app
app --> cw
tgw .. consumer
@enduml