@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Storage/S3.puml
!include AWSPuml/Analytics/KinesisDataStreams.puml
!include AWSPuml/Analytics/Glue.puml
!include AWSPuml/Analytics/Athena.puml
!include AWSPuml/Analytics/OpenSearchService.puml
!include AWSPuml/ApplicationIntegration/EventBridge.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/SecurityIdentityCompliance/KMS.puml
!include AWSPuml/ManagementGovernance/CloudWatch.puml

left to right direction
skinparam shadowing false

rectangle "AWS Analytics Account" {
  KinesisDataStreams(kds, "Kinesis Data Streams")
  EventBridge(eb, "EventBridge")
  Lambda(fn, "Lambda enrichment")
  S3(raw, "S3 raw zone")
  Glue(glue, "Glue catalog / ETL")
  S3(curated, "S3 curated zone")
  Athena(athena, "Athena")
  OpenSearchService(os, "OpenSearch")
  KMS(kms, "KMS keys")
  CloudWatch(cw, "CloudWatch")
}

kds --> fn
 eb --> fn
fn --> raw
raw --> glue
glue --> curated
curated --> athena
curated --> os
kms .. raw
kms .. curated
cw .. fn
cw .. glue
cw .. os
@enduml
