@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/Storage/all.puml

left to right direction
skinparam shadowing false

rectangle "AWS Organization" {
  rectangle "Network Account" {
    TransitGateway(tgw, "Transit Gateway")
    rectangle "Inspection VPC 10.0.0.0/16" {
      rectangle "AZ-a firewall subnet" {
        NetworkFirewall(nfwa, "AWS Network Firewall")
      }
      rectangle "AZ-b firewall subnet" {
        NetworkFirewall(nfwb, "AWS Network Firewall")
      }
      rectangle "Egress subnet AZ-a" {
        VPCNATGateway(nata, "NAT Gateway")
      }
      rectangle "Egress subnet AZ-b" {
        VPCNATGateway(natb, "NAT Gateway")
      }
      VPCInternetGateway(igw, "Internet Gateway")
    }
    CloudWatch(cw, "Firewall metrics and alarms")
    SimpleStorageService(logs, "Central firewall logs")
  }

  rectangle "Production Account" {
    rectangle "Application VPC 10.10.0.0/16" {
      VirtualPrivateCloud(appvpc, "Private application subnets")
    }
  }

  rectangle "Data Account" {
    rectangle "Data VPC 10.20.0.0/16" {
      VirtualPrivateCloud(datavpc, "Private analytics subnets")
    }
  }
}

appvpc --> tgw
datavpc --> tgw
tgw --> nfwa
tgw --> nfwb
nfwa --> nata
nfwb --> natb
nata --> igw
natb --> igw
nfwa ..> logs
nfwb ..> logs
cw .. nfwa
cw .. nfwb
@enduml