@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Storage/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
APIGateway(edge,"API Gateway","global API entry")
Lambda(regionA,"Lambda","Region A application")
Lambda(regionB,"Lambda","Region B application")
SimpleStorageService(static,"S3","static assets")
CloudWatch(cw,"CloudWatch","health and failover telemetry")
edge --> regionA
edge --> regionB
edge --> static
regionA --> cw
regionB --> cw
@enduml