@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Containers/all.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Storage/all.puml
left to right direction
ElasticKubernetesService(eks,"Amazon EKS")
CloudWatch(cw,"CloudWatch Metrics and Logs")
SimpleNotificationService(sns,"SNS Alert Routing")
SimpleStorageService(s3,"Long-term Log Archive")
eks --> cw
cw --> sns
cw --> s3
@enduml