@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/SecurityIdentityCompliance/WAF.puml
!include AWSPuml/NetworkingContentDelivery/APIGateway.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ManagementGovernance/CloudWatch.puml
left to right direction
WAF(waf,"AWS WAF","global web protection")
APIGateway(apiA,"Regional API A","Region A")
APIGateway(apiB,"Regional API B","Region B")
Lambda(appA,"Application Region A","compute")
Lambda(appB,"Application Region B","compute")
DynamoDB(ddbA,"DynamoDB Region A","global data")
DynamoDB(ddbB,"DynamoDB Region B","global data")
SimpleStorageService(s3A,"S3 Region A","objects")
SimpleStorageService(s3B,"S3 Region B","replicated objects")
CloudWatch(cw,"CloudWatch","health monitoring")
waf --> apiA
waf --> apiB
apiA --> appA
apiB --> appB
appA --> ddbA
appB --> ddbB
ddbA <--> ddbB
s3A <--> s3B
appA --> cw
appB --> cw
@enduml
