@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Database/all.puml
!include AWSPuml/Storage/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
APIGateway(global,"API Gateway","global application entry")
Lambda(appA,"Lambda","Region A application")
Lambda(appB,"Lambda","Region B application")
DynamoDB(dataA,"DynamoDB","Region A state")
DynamoDB(dataB,"DynamoDB","Region B state")
SimpleStorageService(s3A,"S3","Region A objects")
SimpleStorageService(s3B,"S3","Region B replicated objects")
CloudWatch(cw,"CloudWatch","regional health")
global --> appA
global --> appB
appA --> dataA
appB --> dataB
dataA <--> dataB
s3A <--> s3B
appA --> cw
appB --> cw
@enduml