@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml

CloudTrail(ct, "Deception Activity", "honeypot audit events")
GuardDuty(gd, "Threat Detection", "suspicious activity")
SecurityLake(sl, "Security Lake", "central deception telemetry")
SecurityHub(sh, "Security Hub", "finding aggregation")
Detective(det, "Detective", "investigation context")
OpenSearchService(os, "OpenSearch", "hunt and investigation")
EventBridge(eb, "EventBridge", "finding routing")
Lambda(fn, "Honeypot Processor", "telemetry enrichment")
SimpleNotificationService(sns, "SNS", "analyst notification")

ct --> sl
gd --> sh
sh --> det
sh --> eb
eb --> fn
fn --> sns
sl --> os
sh --> os
@enduml
