@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
Lambda(honeypot,"Lambda","isolated deception workload")
CloudWatch(telemetry,"CloudWatch","deception telemetry")
EventBridge(events,"EventBridge","event routing")
SecurityLake(lake,"Security Lake","central security data")
OpenSearchService(search,"OpenSearch","investigation views")
SecurityHub(hub,"Security Hub","finding aggregation")
Detective(det,"Detective","investigation context")
honeypot --> telemetry
telemetry --> events
events --> lake
lake --> search
lake --> hub
hub --> det
@enduml