@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
DirectConnect(dx,"Direct Connect","primary hybrid path")
SitetoSiteVPN(vpn,"Site-to-Site VPN","backup path")
TransitGateway(tgw,"Transit Gateway","hybrid routing hub")
VirtualPrivateCloud(shared,"Shared Services VPC","DNS services")
VirtualPrivateCloud(app,"Application VPC","private workloads")
CloudWatch(cw,"CloudWatch","DNS and network telemetry")
dx --> tgw
vpn --> tgw
tgw --> shared
tgw --> app
shared --> app
shared --> cw
app --> cw
@enduml