@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
VirtualPrivateCloud(consumer,"Consumer VPC","private client workloads")
VirtualPrivateCloud(provider,"Provider VPC","private shared service")
TransitGateway(tgw,"Transit Gateway","optional shared routing")
CloudWatch(cw,"CloudWatch","connection and service telemetry")
consumer --> provider
consumer ..> tgw
provider --> cw
consumer --> cw
@enduml