@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/PrivateLink.puml
!include AWSPuml/NetworkingContentDelivery/TransitGateway.puml
!include AWSPuml/NetworkingContentDelivery/VirtualPrivateCloud.puml
!include AWSPuml/Containers/ElasticKubernetesService.puml
!include AWSPuml/ManagementGovernance/CloudWatch.puml
left to right direction
rectangle "Consumer VPC 10.10.0.0/16" {
  ElasticKubernetesService(consumer,"Consumer EKS","private client")
}
rectangle "Provider VPC 10.40.0.0/16" {
  VirtualPrivateCloud(provider,"Private Service Network","provider VPC")
}
PrivateLink(pl,"AWS PrivateLink","private service access")
TransitGateway(tgw,"Transit Gateway","optional network hub")
CloudWatch(cw,"CloudWatch","service telemetry")
consumer --> pl
pl --> provider
provider --> cw
tgw ..> consumer
@enduml
