@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml

CloudTrail(ct, "Organization Audit", "central account activity")
GuardDuty(gd, "GuardDuty", "organization threat detection")
SecurityLake(sl, "Log Archive", "central security evidence")
SecurityHub(sh, "Security Hub", "finding aggregation")
Detective(det, "Investigation", "security context")
OpenSearchService(os, "Operations Search", "central operational views")
EventBridge(eb, "Account Events", "governance event routing")
Lambda(fn, "Account Automation", "landing zone automation")
SimpleNotificationService(sns, "Governance Alerts", "operator notification")

ct --> sl
gd --> sh
sh --> det
sh --> eb
eb --> fn
fn --> sns
sl --> os
sh --> os
@enduml
