@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Database/all.puml
!include AWSPuml/Storage/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
APIGateway(entry,"API Gateway","application entry")
Lambda(primary,"Lambda","primary Region application")
Lambda(recovery,"Lambda","recovery Region application")
DynamoDB(dataPrimary,"DynamoDB","primary data")
DynamoDB(dataRecovery,"DynamoDB","replicated recovery data")
SimpleStorageService(objectsPrimary,"S3","primary objects")
SimpleStorageService(objectsRecovery,"S3","replicated objects")
CloudWatch(cw,"CloudWatch","health and recovery telemetry")
entry --> primary
entry --> recovery
primary --> dataPrimary
recovery --> dataRecovery
dataPrimary <--> dataRecovery
objectsPrimary <--> objectsRecovery
primary --> cw
recovery --> cw
@enduml