@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/Database/all.puml
!include AWSPuml/Storage/all.puml
left to right direction
VirtualPrivateCloud(vpc,"Application VPC","multi-AZ private workload network")
NetworkFirewall(fw,"Network Firewall","central inspection")
VPCNATGateway(nat,"NAT Gateway","controlled egress")
APIGateway(api,"API Gateway","application ingress")
Lambda(app,"Lambda","private application tier")
DynamoDB(db,"DynamoDB","application state")
SimpleStorageService(logs,"S3","central logs")
CloudTrail(trail,"CloudTrail","API audit")
CloudWatch(cw,"CloudWatch","metrics and alarms")
api --> app
app --> db
app --> fw
fw --> nat
vpc --> app
trail --> logs
cw --> logs
@enduml