@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
APIGateway(access,"API Gateway","identity-aware application entry")
Lambda(authz,"Lambda","authorization and policy evaluation")
VirtualPrivateCloud(private,"Private Application VPC","private service boundary")
CloudTrail(trail,"CloudTrail","access audit trail")
CloudWatch(cw,"CloudWatch","access telemetry and alarms")
access --> authz
authz --> private
authz --> trail
authz --> cw
@enduml