@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
left to right direction
CloudTrail(ct,"CloudTrail","organization trail")
GuardDuty(gd,"GuardDuty","threat detections")
SecurityLake(sl,"Security Lake","OCSF data lake")
SecurityHub(sh,"Security Hub","finding aggregation")
Detective(det,"Detective","investigation")
OpenSearchService(os,"OpenSearch","search and SIEM views")
EventBridge(eb,"EventBridge","finding routing")
Lambda(fn,"Lambda","enrichment and response")
SimpleNotificationService(sns,"SNS","human notification")
ct --> sl
gd --> sh
sh --> det
sh --> eb
eb --> fn
fn --> sns
sl --> os
sh --> os
@enduml