@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/ManagementGovernance/all.puml
left to right direction
EventBridge(events,"EventBridge","security event routing")
Lambda(normalize,"Lambda","normalization and enrichment")
SecurityLake(lake,"Security Lake","governed security data")
OpenSearchService(search,"OpenSearch","SIEM and investigation")
SecurityHub(hub,"Security Hub","finding aggregation")
Detective(det,"Detective","entity investigation")
CloudWatch(cw,"CloudWatch","pipeline health")
events --> normalize
normalize --> lake
lake --> search
lake --> hub
hub --> det
normalize --> cw
@enduml