@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/ManagementGovernance/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml

CloudTrail(ct, "CloudTrail", "organization audit activity")
GuardDuty(gd, "GuardDuty", "threat detections")
SecurityLake(sl, "Security Lake", "central security data")
SecurityHub(sh, "Security Hub", "finding aggregation")
Detective(det, "Detective", "investigation context")
OpenSearchService(os, "OpenSearch", "search and SIEM views")
EventBridge(eb, "EventBridge", "finding routing")
Lambda(fn, "Security Enrichment", "triage and enrichment")
SimpleNotificationService(sns, "SNS", "human alerts")

ct --> sl
gd --> sh
sh --> det
sh --> eb
eb --> fn
fn --> sns
sl --> os
sh --> os
@enduml
