@startuml
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v23.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/ManagementGovernance/all.puml

DirectConnect(svc01, "Workload Connectivity", "AWS Direct Connect", "Approved primary private path")
SitetoSiteVPN(svc02, "Backup Connectivity", "AWS Site-to-Site VPN", "Resilient alternate path")
TransitGateway(svc03, "Transit Gateway", "AWS Transit Gateway", "Central routing hub")
VirtualPrivateCloud(svc04, "Inspection VPC", "Amazon VPC", "Central security boundary")
NetworkFirewall(svc05, "Network Firewall", "AWS Network Firewall", "Stateful inspection")
VPCNATGateway(svc06, "NAT Gateway", "Amazon VPC NAT Gateway", "Controlled egress")
VirtualPrivateCloud(svc07, "Application VPC", "Amazon VPC", "Private application workloads")
VirtualPrivateCloud(svc08, "Data VPC", "Amazon VPC", "Private analytics workloads")
CloudWatch(svc09, "CloudWatch", "Amazon CloudWatch", "Network and firewall telemetry")

svc01 --> svc03
svc02 --> svc03
svc03 --> svc04
svc04 --> svc05
svc05 --> svc06
svc03 --> svc07
svc03 --> svc08
svc05 --> svc09
@enduml